

CREATE TABLE "AcquiringOper" (
                                 "id" BIGSERIAL PRIMARY KEY, -- аналог Identity в PostgreSQL
                                 "term" INTEGER NOT NULL,
                                 "code" VARCHAR(50) NOT NULL,
                                 "Merchant" VARCHAR(10),
                                 "OrderID" VARCHAR(50),
                                 "SessionID" VARCHAR(50),
                                 "OrderIDEncrypted" VARCHAR(50),
                                 "PAN" VARCHAR(50),
                                 "AmountCur" DOUBLE PRECISION,
                                 "Amount" DOUBLE PRECISION,
                                 "note" VARCHAR(50),
                                 "Articul" VARCHAR(50),
                                 "try_count" INTEGER NOT NULL DEFAULT 1,
                                 "status" INTEGER NOT NULL DEFAULT 1,
                                 "Currency" VARCHAR(10) DEFAULT NULL,
                                 "Date" DATE NOT NULL DEFAULT CURRENT_DATE,
                                 "inputdate" VARCHAR(50) NOT NULL DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYMMDDHH24MISS'),
                                 "outputdate" VARCHAR(50),
                                 "phone" VARCHAR(20),
                                 "TranDateTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 "ResponseCode" VARCHAR(10),
                                 "ResponseDescription" VARCHAR(250),
                                 "CardHolderName" VARCHAR(50),
                                 "Brand" VARCHAR(20),
                                 "ApprovalCode" VARCHAR(20),
                                 "OrderDescription" VARCHAR(550),
                                 "AcqFee" VARCHAR(10),
                                 "CardID" VARCHAR(50),
                                 "Url_request" VARCHAR(500),
                                 "ApproveURL" VARCHAR(500),
                                 "DeclineURL" VARCHAR(500),
                                 "CancelURL" VARCHAR(500),
                                 "AgentID" VARCHAR(50),
                                 "ACSURL" TEXT,
                                 "PaReq" TEXT,
                                 "MD" TEXT,
                                 "Month1" VARCHAR(100),
                                 "Year1" VARCHAR(100),
                                 "CVC1" VARCHAR(100),
                                 "Respond" TEXT,
                                 "Request" TEXT,
                                 "statuscallback" INTEGER NOT NULL DEFAULT 1,
                                 "sendcallback" VARCHAR(50)
);

